---

- hosts: all
  become: true
  tasks:
  
   - name: install httpd apache and php support package
     package:
        name: 
           - "{{ apache_package }}"
           - "{{ php_package }}"

        state: latest
        update_cache: yes



   

